version: '3'
services:
  app:
    build: ./app
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
  mongo:
    image: "mongo"
    ports:
      - "27019:27017"
