version: '3'
services:
  app:
    build: ./app
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
  mongo:
    image: "mongo"
    ports:
      - "27018:27017"
