version: '3'
services:
  app:
    build: ./app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
  # api:
  #   image: "shopster-app"
  #   network_mode: bridge
  #   ports:
  #     - "3001:3001"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
